# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('choice', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('review', models.TextField(max_length=2000)),
                ('rating', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ManyToManyField(related_name='books', to='login_and_reg.User')),
            ],
        ),
    ]
