# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170819_1218'),
        ('book_authors', '0005_remove_book_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='users.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ManyToManyField(related_name='uploads', to='users.User'),
        ),
    ]
